<?php
namespace common\widgets;

use Yii;
use yii\base\Widget;

class CountryPermition extends Widget
{
    public $model;
    public $type = 'allowed';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        // render allowed countries
        $type = $this->type;
        $allowedArr = $this->model->$type;
        $result = [];

        if (!empty($allowedArr)) {
            foreach ($allowedArr as $allowed) {
                $result[] = $allowed->title;
            }
        }

        return implode(', ', $result);
    }
}