<?php
namespace common\widgets;

use common\models\Review;
use Yii;
use yii\base\Widget;
use yii\helpers\ArrayHelper;

class CountryPermition extends Widget
{
    public $type = 'allowed';
    public $review_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        // render allowed countries
        $review = Review::findOne($this->review_id);
        $type = $this->type;
        $allowedArr = $review->$type;
        $result = [];

        if (!empty($allowedArr)) {
            foreach ($allowedArr as $allowed) {
                $result[] = $allowed->title;
            }
        }

        echo implode(', ', $result);
    }
}