<?php
namespace common\widgets;

use common\models\Country;
use Yii;
use yii\base\Widget;
use yii\helpers\Html;

class Countries extends Widget
{
    public $countries;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->countries = Country::find()->asArray()->all();
    }

    public function run()
    {
        $html = $options = '';

        if (!empty($this->countries)) {
            // For test - USA ip
            $ip = Yii::$app->geoip->ip('173.201.183.172');

            foreach ($this->countries as $country) {
                $optionArr = ['option' => $country['id']];

                if ($ip->country == $country['title']) {
                    $optionArr['selected'] = 'selected';
                }

                $options .= Html::tag('option', $country['title'], $optionArr);
            }
        }

        $html = Html::tag('select', $options, ['class' => 'f-select', 'style' => 'width: 200px;']);

        echo $html;
    }
}